7.7. Game RPS
tomOsuch/kodilla-course pull request #12
Opened 2020-08-18 10:54 UTC by tomOsuch

2020-08-18 10:55 UTC, tomOsuch commented
Wstępny zarys interfejsów i klas

2020-08-18 17:14 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/model/PlayerState.java
> +    private int gameCount;
O czym mówi to pole?

2020-08-18 17:14 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/model/PlayerState.java
> +    private int stateGame = 0;
O czym mówi to pole?

2020-08-18 17:14 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +    public void manualGame() {
Co będzie robić ta metoda?

2020-08-18 17:15 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +    public int calculateResultOfGame() {
Co tutaj będzie liczone?

2020-08-24 17:57 UTC, marszelun requested changes

2020-08-24 17:57 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRepository.java
> +public interface GameRepository {
Nie rozumiem idei - dlaczego to się nazywa `GameRepository`. Z reguły nazwy `Repository` używamy na oznaczenie komponentów / serwisów persystujących jakieś modele (np. w bazach danych). Możesz to nazwać po prostu `Game` :)

2020-08-24 17:57 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +    private final int kamien = 1;
Do reprezentacji tego typu wartości najlepiej nadają się wyliczenia, czyli `enum`-y.

2020-08-24 17:57 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +        int gameCount = scanner.nextInt();
Jak już ogarniesz architekture kodu, możesz zabezpieczyć się tutaj przed podaniem nieprawidłowej wartości (np. literek lub zbyt dużej liczby).

2020-08-24 17:57 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/model/PlayerState.java
> +public class PlayerState {
Tak naprawdę ta klasa nie przechowuje stanu gry, tylko jej pierwotną konfigurację (nazwa użytkownika i ilość zwycięstw - to się nie zmienia w trakcie rozgrywki). Sugeruję zmianę nazwy, np. na `GameSettings`,

2020-08-24 17:57 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/model/PlayerState.java
> +    private int gameCount;
Chodzi zapewne o `winsCount`.

2020-08-24 17:57 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRepository.java
> +    int playerSelectionGame();
Nazwy metod powinny być czasownikami. Dwie zaczynające się od `show` są OK, 2 pozostałe - nie.

2020-08-24 17:57 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +        do {
Dla czytelności główna pętla powinna być maksymalnie krótka. Na przykład:
```
do {
    Artefact playerArtefact = playerSelectionGame();
    Artefact computerArtefact = getComputerArtefact();
} while (updatePoints(playerArtefact, computerArtefact))
```
2 metody wewnątrz `do` zwracają odpowiednio ruch gracza i komputera.
Metoda `udpatePoints`:
- oblicza, kto wygrał (najlepiej, jeśli w tym celu wywoła inną metodę prywatną, lub metodę z innej klasy)
- aktualizuje liczniki zwycięstw gracza i komputera (pola w `GameRps`)
- zwraca `true`, jeśli warunek zakończenia nie jest spełniony, `false` - jeśli koniec gry

Po pętli wystarczy sprawdzić, kto ma więcej punktów i wywołać wyświetlenie komunikatu końcowego :)

2020-08-24 17:57 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +            switch (computerSelectionGame) {
W tym wielkim switchu każdy przypadek jest zdublowany. Nie powienieneś jednym ifem sprawdzać pary <papier, kamień>, a później drugim <kamień, papier>, bo to jest taka sama relacja.

Można to zaimplementować na różne inne sposoby. Na przykład:
`Map<Set<Artefact, Artefact>, Artefact> winningArtefact` - mapa, gdzie kluczem jest para artefaktów, a wartością zwycięzki artefakt
`Map<Artefact, Set<Artefact>> winsWith` - mapa, gdzie kluczem jest jeden artefakt, a wartością lista artefaktów, które pokonuje (czyli jeśli drugi artefakt jest na liście, to klucz wygrywa, jeśli nie - remis lub przegrywa).

W każdym razie warto oddzielić samą logikę który z dwóch wygrywa od przypisania, który jest komputera a który gracza. To może być w innej metodzie:
`Player selectWinner(Artefact playerArtefact, Artefact computerArtefact)` - przyda się jeszcze `enum Player { PLAYER, COMPUTER }`

2020-08-26 06:20 UTC, marszelun requested changes
Należy jeszcze popracować nad rozdzieleniem logiki gry od obsługi we/wy i flow.
Teraz całość jest skupiona w `GameRps`, ta klasa ma zbyt wiele odpowiedzialności.

Klasa odpowiedzialna za logikę gry powinna:
- "wykonywać" ruch gracza,
- wykonywać ruch komputera,
- sprawdzać warunki wygranej

Klasa odpowiedzialna za przepływ powinna w pętli:
- przyjmować od gracza wybór 1,2,3
- przekształcać to na ENUM i "wywołać" ruch w klasie z logiką
- sprawdzać, czy spełniony jest warunek zwycięstwa, jeśli tak to wyświetlać stosowny komunikat

Klasa od logiki powinna być zaprojektowana tak, aby:
- łatwo było przetestować ją jednostkowo,
- jeśli postanowisz napisać wersję 2.0 z interfejsem graficznym zamiast konsolowym, to ta klasa nie powinna się zmienić ani o jeden przecinek

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/RpsRunner.java
> +        GameRps gameRps = new GameRps(0, 0);
Skoro i tak inicjalizujesz `GameRps` zawsze zerami, to możesz te przypisania mieć od razu przy definicji pól w `GameRps` i odpuścić sobie w ogóle konstruktor.

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/RpsRunner.java
> +        gameRps.showIntroGame();
Bardziej gramatycznie `showIntroGame()`

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/RpsRunner.java
> +        gameRps.startPlayingGame();
Ta nazwa nie do końca oddaje właściwy sens. Jeśli metoda ma w nazwie `start`, to spodziewałbym się, że rozpoczyna jakiś proces (np. asynchronicznie, w innym wątku) i szybko zwraca sterowanie. Tutaj metoda uruchamia główną pętlę gry i działa tak długo, jak trwa gra - może po prostu `playGame()`?

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/Artefact.java
> +    KAMIEN, NOZYCE, PAPIER;
Raczej trzymamy się angielskiego nazewnictwa w kodzie.

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +    public GameRps(int computerResult, int playerResult) {
Jak pisałem wcześniej, konstruktor niepotrzebny - możesz zainicjować od razu pola zerami.

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +            int selection = scanner.nextInt();
Jeśli skanowanie wejścia użytkownika jest czymś odrębnym od `playerSelectionGame`, to proponuję wynieść to do odrębnej metody.

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +        showResultGame();
`showGameResult`

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +        if (playerResult > computerResult){
Spacja przed `{`.

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +        winsWith.put(Artefact.NOZYCE, artefactWinsofNozyce);
1. Za każdym wywołaniem `selectWinner` tworzona jest od nowa ta mapa. To powinno być utworzone raz, ponieważ jakkolwiek długo by nie trwała gra, obiekt `winsWith` jest niezmienny.
2. Poszukaj zgrabniejszego sposobu inicjalizacji zbiorów. Korzystasz przecież z Javy 14 ;)
3. Skoro każdy ze zbiorów ma jeden element, to znaczy że nie potrzebujesz zbiorów tylko po protu `Map<Artefact, Artefact>`. Proponowałem ze zbiorami, bo w głowie miałem wersję gry, gdzie jeszcze jest studnia (wtedy zbiór miałby sens).

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +        if (winsWith.containsKey(playerArtefact) && winsWith.get(playerArtefact).contains(computerArtefact)) {
Patrz uwaga wyżej - nie potrzebujesz zbiorów - więc uprości się to do `computerArtefact.equals(winsWith.get(playerArtefact))`

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +        return playerResult == gameSettings.getWinsCount() || computerResult == gameSettings.getWinsCount();
Do czego Ci ta wartość zwracana, skoro i tak jej nigdzie nie wykorzystujesz?

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/Player.java
> +    PLAYER, COMPUTER, REMIS;
Tutaj w jednym enumie wymieszałeś 2 abstrakcje: gracz / komputer i rezultat pojedynczej rozgrywki.
Albo niech to się nazywa `Result` i ma wartości `PLAYER_WINS, COMPUTER_WINS, DRAW`, albo trzeba to rozbić na `Player` i `Result`.

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/SelectionSettings.java
> +            case 1 -> artefactSelection = Artefact.KAMIEN;
Czy jesteś pewny tego switcha? Moim zdaniem zawsze zwraca `NOZYCE`...

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/test/java/com/kodilla/rps/game/GameRpsTestSuite.java
> +        assertTrue(updatePointResult);
Tutaj testujesz wartość, która w kodzie nie jest nigdzie używana.

2020-08-26 06:20 UTC, marszelun commented on kodilla-rps/src/test/java/com/kodilla/rps/game/SelectionSettingsTestSuite.java
> +    void testSelectionArtefact() {
Dobry test, ale czemu tylko kamień? Nożyce i Papier nie zasługują na testy ;) ?

2020-08-26 08:54 UTC, tomOsuch commented on kodilla-rps/src/main/java/com/kodilla/rps/game/SelectionSettings.java
> +            case 1 -> artefactSelection = Artefact.KAMIEN;
właśnie przetestowałem tą metodę dla trzech wartości int: 1, 2, 3 i przechodzi na zielono. Chyba, że czegoś nie widzę :(

2020-08-26 09:17 UTC, tomOsuch commented on kodilla-rps/src/test/java/com/kodilla/rps/game/GameRpsTestSuite.java
> +        assertTrue(updatePointResult);
Faktycznie, w założeniu metoda miała być wykorzystana przy fladze dla pętli do { ... } while a niestety nie była zaimplementowana. już to zmieniłem i będzie to przy następnym update

2020-08-27 16:08 UTC, marszelun requested changes
Oprócz uwag, które zostawiłem przy kodzie - przemyśl proszę nazwy klas. Spróbuj też popatrzeć "z lotu ptaka" na całą architekturę klas - pomoże zrobienie rysunku / diagramu, która klasa zależy od której (które metody w innych klasach wywołuje).

2020-08-27 16:08 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +    public boolean updatePoint(Result wins, GameSettings gameSettings) {
`GameSettings` jest niezmienne - mogłoby być polem w tej klasie, nie musi być przekazywane w każdym wywołaniu `updatePoint`.

2020-08-27 16:08 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +        Map<Artefact, Artefact> winsWith = artefactMap.getMap();
Akurat tutaj - moim zdaniem nie potrzebujesz odrębnej klasy do przechowywania tej mapy. Możesz  ją spokojnie ustawiać raz w konstruktorze - albo żeby nauczyć się czegoś nowego - mieć ją w polu statycznym i użyć statycznego bloku inicjującego (do wygooglowania).

2020-08-27 16:08 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +        if (winsWith.containsKey(playerArtefact) && winsWith.get(playerArtefact).equals(computerArtefact)) {
To samo krócej: `computerArtefact.equals(winsWith.get(playerArtefact))`
Operacja `foo.equals(null)` jest bezpieczna i zwraca `false`. Tutaj `computerArtefact` na pewno nie będzie `null`-em.

2020-08-27 16:08 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/Application.java
> +        } while (!flaga);
Nie potrzebujesz zmiennej `flaga`! Wystarczy, że wnętrze ifa z linii 26 przeniesiesz do "argumentu" `while` tutaj.

2020-08-27 16:08 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/FacadeGame.java
> +    private GameRps gameRps = new GameRps();
Coś jest nie tak z `GameRps` - raz tworzysz w głównej klasie, drugi raz tutaj... Raczej obiekt tej klasy powinien być tworzony raz i ewentualnie przekazywany.

2020-08-27 16:08 UTC, marszelun commented on kodilla-rps/src/test/java/com/kodilla/rps/game/GameRpsTestSuite.java
> +        assertEquals(PLAYER_WINS, result);
Każdy możliwy rezultat powinien być przetestowany.

2020-08-30 09:04 UTC, marszelun requested changes

2020-08-30 09:04 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/ShowGame.java
> +    void showResultGame();
Tu by mogła dojść metoda dotycząca odbierania ustawień od użytkownika.

2020-08-30 22:32 UTC, tomOsuch commented on kodilla-rps/src/main/java/com/kodilla/rps/game/LogicGame.java
> +    boolean updatePoint(Result wins);
Tutaj raczej chodziło o updatePoints

2020-08-30 23:01 UTC, tomOsuch commented on kodilla-rps/src/main/java/com/kodilla/rps/game/LogicGameRps.java
> +        Map<Artefact, Artefact> winsWith = artefactMapWins;
W sumie racja przypisanie jest bez sensu.

2020-08-31 09:48 UTC, tomOsuch commented on kodilla-rps/src/main/java/com/kodilla/rps/game/ShowGame.java
> +    void showResultGame();
Mam rozumieć ze tutaj chodzi o pobieranie w konsoli od użytkownika danych ale samo tworzenie ustawień miało by się odbyć w klasie LogicGameRps?

2020-08-31 15:53 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/ShowGame.java
> +    void showResultGame();
W jakiej postaci chciałbyś zwrócić wybór użytkownika? W tym przypadku chyba najlepiej w postawi obiektu ustawień, moim zdaniem nie ma potrzeby takiego rozbicia jak piszesz.

2020-08-31 21:25 UTC, tomOsuch commented on kodilla-rps/src/main/java/com/kodilla/rps/game/ShowGame.java
> +    void showResultGame();
chodzi o utworzenie metody w Klasie z logiką która będzie zwracała obiekt typu GameSettings.

2020-08-31 22:41 UTC, tomOsuch commented on kodilla-rps/src/main/java/com/kodilla/rps/game/LogicGame.java
> +    Artefact playerSelectionArtefact(int selectionNumber);
Tutaj przeniosłem tą metodę do klasy ShowGameRps ale zastanawiam się czy nie lepiejutworzyć nową klase np Factory która by posiadała dwie metody:
1. selectionOfArtefact(int selection)
2. playerSelectionOfArtefact(int selectionNumber)

2020-09-01 14:29 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/SelectionSettings.java
> +            case 1 -> artefactSelection = Artefact.KAMIEN;
Nie zwróciłem uwagi, że to nowa składnia z Javy 14. W takim przypadku powinno to wyglądać nieco inaczej:
```
Artefact artefactSelection = switch(selection) {
    case 1 -> Artefact.KAMIEN;
    ...
}
```

2020-09-01 14:30 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameRps.java
> +        if (winsWith.containsKey(playerArtefact) && winsWith.get(playerArtefact).equals(computerArtefact)) {
Uwaga niezrealizowana - nie potrzebujesz tutaj `contains`.

2020-09-07 14:16 UTC, marszelun approved these changes

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/GameLogic.java
> +    GameResult updatePointsAndGetGameResult(RoundResult wins);
Czemu tutaj nazwa argumentu `wins`? Może nikt nie wygrać (remis rundy).

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/RpsGame.java
> +
Niepotrzebny odstęp 2 linii.

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/RpsLogic.java
> +
Niepotrzebne 3 puste linie.

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/RpsLogic.java
> +    static Map<Artefact, Artefact> artefactMapWins;
Czemu ta mapa nie jest `private`?

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/RpsLogic.java
> +    static Map<Artefact, Artefact> artefactMapWins;
Zmieniłbym jeszcze nieco nazwę na `artefactWinsWith`:
- słowo `map` jest niepotrzebne w nazwie, widać że to mapa
- `with` zwraca uwagę na "kierunek" mapy - że klucz mówi co wygrywa, a wartość - z czym

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/RpsLogic.java
> +        switch (wins){
Brak spacji przed `{`

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/RpsLogic.java
> +        return artefacts.get(random.nextInt(3));
Bardziej elegancko byłoby użyć tutaj `artefacts.size()` zamiast `3` - jeśli dodasz do gry czwartę figurę studnia, to przynajmniej tej metody nie będziesz musiał zmieniać.

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/game/RpsLogic.java
> +
Niepotrzebne 2 puste linie.

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/model/GameSettings.java
> +    private String username;
`final`

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/main/java/com/kodilla/rps/model/GameSettings.java
> +    private int winsCount;
`final`

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/test/java/com/kodilla/rps/game/RpsLogicTestSuite.java
> +
Aż 3 puste linie?

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/test/java/com/kodilla/rps/game/RpsLogicTestSuite.java
> +        assertEquals(PLAYER_WINS, resultPlayerWins);
Można by krócej - od razu `assertEquals(PLAYER_WINS, gameRps.selectWinner(ROCK, SCISSORS)` itd. - 6 przypadków do ogrania.

2020-09-07 14:16 UTC, marszelun commented on kodilla-rps/src/test/java/com/kodilla/rps/game/RpsLogicTestSuite.java
> +        assertEquals(GameResult.COMPUTER_WINS, resultComputerWinner);
Ten test obnaża pewną słabość metody `updatePointsAndGetGameResult` - można "grać dalej", mimo osiągnięcia zakładanej liczby punktów.
Najlepiej rozbić to na 2 testy, możesz jeszcze pośrednio sprawdzać, czy jest `NO_RESULT` (przeplatanie kilku sekcji when...then).

2020-09-09 13:57 UTC, tomOsuch commented
Mam nadzieje że o to chodziło w tych testach ;)

2020-09-09 23:18 UTC, merged