task_13_2_solid_and_dry
tomOsuch/kodilla-course pull request #17
Opened 2020-09-25 22:01 UTC by tomOsuch

2020-09-26 14:46 UTC, marszelun requested changes

2020-09-26 14:46 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/ProductOrderService.java
> +public class ProductOrderService {
Tutaj trochę pomieszanie nazw. Klasa wygląda tak, jakby miała implementować `OrderService`. Może lepiej nazwać ją - zgodnie z przykładem - `OrderProcessor`? (zwłaszcza, że ma metodę `process`).

2020-09-26 20:24 UTC, tomOsuch commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/OrderDto.java
> +    public boolean isOrder;
Faktycznie to pole nie ma sensu. zamiast tego zrobiłem mapowanie na zamówienie. również w tym celu zmieniłem metodę process na void.

2020-09-26 20:25 UTC, tomOsuch commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/ProductOrderService.java
> +public class ProductOrderService {
Tutaj zasugerowałem sie poleceniem zadania ale faktycznie też lepiej mi pasowało OrderProcessor

2020-09-26 20:26 UTC, tomOsuch commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/MailService.java
> +    public void sendMailFromUser(User user) {
Pomyłka ;)

2020-09-27 07:47 UTC, marszelun requested changes

2020-09-27 07:47 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/OrderDto.java
> +    public LocalDateTime dateOrder;
`orderDate`

2020-09-27 07:47 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/OrderProcessor.java
> +    public void process(OrderRequest orderRequest) {
Metoda powinna zwracać obiekt typu `OrderDto`

2020-09-27 07:47 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/OrderProcessor.java
> +        boolean isOrder = orderService.order(orderRequest.getUser(), orderRequest.getPrice(), orderRequest.getOrderDate());
`isOrdered` - w tej zmiennej przechowujesz status - czy zamówienie się powiodło, prawda?

2020-09-27 07:47 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/InformationService.java
> +    void sendmailToUser(User user);
Wcześniejsza uwaga niezrealizowana. Jeśli intefejs jest ogólny - tu `InformationService`, nazwa metody powinna być na tyle ogólna, by pasowały do niej różne implementacje. Proponuję `informUser` albo `notifyUser`.

2020-09-27 07:47 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/InformationService.java
> +    void sendmailToUser(User user);
Ewentualnie jeśli chcesz zachować słowo `send`, może być np. `sendNotification`

2020-09-27 07:47 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/ComputerOrderService.java
>  public class ComputerOrderService implements OrderService {
W prawdziwym sklepie internetowym, myślisz że dla różnych kategorii zamówień byłyby różne klasy? Czy raczej szukałbyś sposobu na napisanie kodu raz tak, aby poprawnie działał dla wszystkich kategorii?

2020-09-27 07:47 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/OrderDto.java
> -    public boolean isOrder;
W tej klasie powinieneś przechować informację o statusie zamówienia (to jest klasa, którą reprezentujesz wynik całej operacji składania zamówienia - powinna być zwracana z metody `process`).
Pole typu `boolean` ze statusem było OK, tylko nazwa -> `isOrdered` :)
Możesz zastosować również `enum`, np. `OrderStatus.ORDERED`, `OrderStatus.CANCELLED` itp.

2020-09-27 12:26 UTC, tomOsuch commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/OrderProcessor.java
> +        boolean isOrder = orderService.order(orderRequest.getUser(), orderRequest.getPrice(), orderRequest.getOrderDate());
Tak ta zmienna mówi o czy zamówienie zostało założone czy jednak nie.

2020-09-27 13:20 UTC, tomOsuch commented
z implementacji produktów klasami zmieniłem na  utworzenie jednej klasy która tworzy na razie Listę (tutaj zastanawiam się nad utworzeniem mapy)

2020-09-27 16:47 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/OrderProcessor.java
> +        boolean isOrder = orderService.order(orderRequest.getUser(), orderRequest.getPrice(), orderRequest.getOrderDate());
No to powinna nazywać się np. `isOrdered` :) albo `isOrderSucceful`

2020-09-27 16:52 UTC, marszelun requested changes
Jesteśmy bliżej dobrego kodu, ale jeszcze niewystarczająco blisko na approve ;)
Oprócz uwagi przy ProductType, zastanów się nad strukturą pakietów - wszystko jest bezpośrednio w `shop`, przemyśl podział tego na pakiety (oczywiście wszystkie mogą być wewnątrz `shop`).

2020-09-27 16:52 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/ProductType.java
> +public class ProductType {
Nie rozumiem tej klasy. Typ produktu? 
Wystarczy tutaj po prostu klasa `Product`, może mieć pola np. `String name` i `BigDecimal price`.
`OrderRequest` - zamiast `String product`, niech ma np. listę produktów `List<Product> products`. Nie jest wtedy potrzebne pole `price` w `OrderRequest` (cena jest cechą produktu, nie zamówienia).

2020-09-27 16:52 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/OrderProcessor.java
> +        OrderDto orderDto = null;
Ta zmienna jest nieużywana.

2020-09-28 15:33 UTC, marszelun requested changes

2020-09-28 15:33 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/components/order/OrderRequest.java
> +      products = List.of(new Product("Komputer", new BigDecimal("182.5")),
Nie potrzebujesz żadnej listy produktów. Po prostu stwórz odpowiedni produkt w `OrderRequestRetriever`.

2020-09-28 15:33 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/components/order/OrderRequestRetriever.java
> +        User user = new User("Jan", "Kowalski", "Ul. Kwiatowa 13", "jan.kowalski@test.pl");
To samo zrób z produktem ;)

2020-09-28 16:32 UTC, tomOsuch commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/shop/components/order/OrderDto.java
> +    public User user;
W sumie tutaj zasugerowałem się konstrukcją klasy z przykładu ale tak naprawdę jak wczytałem sie w strukturę DTO i przykłady to faktycznie pola powinny być private

2020-09-28 17:07 UTC, marszelun approved these changes

2020-09-28 19:07 UTC, merged