task_13_4_food2door
tomOsuch/kodilla-course pull request #18
Opened 2020-09-27 10:40 UTC by tomOsuch

2020-09-29 16:11 UTC, marszelun requested changes

2020-09-29 16:11 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/model/Product.java
> +
Omówiliśmy na video - produkt powinien mieć w jakiś sposób zapisane informacje o dostawcy.
`count` nie charakteryzuje produktu, to cecha przy produkcie w koszyku.
Produkt powinien mieć cenę.

2020-09-29 16:11 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/model/Provider.java
> +public class Provider {
interfejs z metodą `process`, 3 implementacje (po jednej dla każdego dostawcy)

2020-09-29 16:11 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderDto.java
> +    private final Provider provider;
Akurat `Provider` tu nie pasuje - zamówienie może mieć co najwyżej mapę zamówionych produktów (produkt -> ilość).

2020-09-29 16:11 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderProcessor.java
> +        boolean isOrderSuccessful = orderService.order(orderRequest.getUser(), orderRequest.getProvider(), orderRequest.getProduct(), orderRequest.getOrderDate());
Tak jak mówiliśmy na video:
- niech `OrderRequest` ma mapę produktów (produkt -> ilość)
- rozbijamy mapę na n mniejszych map, n = ilość dostawców
- każdą z takich mniejszych map wykorzystujemy do złożenia zamówienia u dostawcy (`Provider::process`)
- ustalamy warunki - jak zamówienie od któregokolwiek z nich się nie powiedzie, rzucamy wyjątek
- informujemy na koncu o sukcesie (a w `catch` o niepowodzeniu)

2020-09-29 16:11 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderRepository.java
> +    void createOrder(User user, Provider provider, Product product, double countProduct, LocalDateTime orderDate);
Tu tez zamiast `Product` -> `Map<Product, Integer>`

2020-09-29 16:11 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderRequest.java
> +    public Product product;
`Product` -> `Map<Product, Integer>`
pole `Provider` niepotrzebne - ma być w `Product`

2020-09-29 16:11 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderRequestRetriever.java
> +        User user = new User(1, "jkowalski", "1234", "jan.kowalski@test.pl", "Ul. Kwiatowa 12");
Tu też będzie inaczej, wynika to ze zmian w innych miejscach.

2020-09-30 01:10 UTC, tomOsuch commented
W sumie chciałbym wiedzieć czy w dobrą stronę idę? Jeśli tak to oczywiście jeszcze testy przede mną ;)

2020-09-30 16:43 UTC, marszelun requested changes

2020-09-30 16:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/model/Product.java
> +    private final Provider provider;
Produkt powinien mieć cenę...

2020-09-30 16:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderDto.java
> +    private final BigDecimal price;
Co to za cena? Suma całego zamówienia? Jeśli tak, to pole powinno się inaczej nazywać, jeśli nie - nie powinno go tutaj być.

2020-09-30 16:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderProcessor.java
> +                .iterator().next();
1. Niepoprawnie użyty `iterator`.`isOrderSuccessfulProvider` będzie zawierać wynik wywołania metody `process` na pierwszym elemencie.
2. Nazwa zmiennej. Jak coś ma na końcu nazwy `Provider`, to jest providerem. Tutaj masz zmienną typu `boolean`, która mówi o jakimś statusie, więc raczej powinna się nazywać `isOrderProviderSuccesful` (chociaż szukałbym nadal zgrabniejszej nazwy).

2020-09-30 16:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderProcessor.java
> +        boolean isOrderSuccessful = orderService.order(orderRequest.getUser(), orderRequest.getProducts(), orderRequest.getOrderDate());
Jaka jest rola `orderService`? Wyżej zamawiasz produkty od trzech dostawców, a tutaj co zamawiasz? Może lepiej umieścić odpytywanie tych 3 dostawców wewnątrz `orderService`?

2020-09-30 16:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderProcessor.java
> +        if (isOrderSuccessfulProvider == isOrderSuccessful) {
Nie rozumiem tego `if`-a. Jeśli oba powyższe procesy zwrócą `false` (czyli nie powiodą się), to ten warunek będzie spełniony. Na pewno o to chodziło?

2020-09-30 16:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderProcessor.java
> +            System.out.println("Wyjątek");
Hmm.... może lepiej użyć `try...catch` ;)

2020-09-30 16:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderRequest.java
> +    public BigDecimal price;
Cena powinna być cechą produktu, nie zamówienia (koszyka).

2020-09-30 16:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/ProviderOrderService.java
> +public class ProviderOrderService implements OrderService {
Nazwałbym to raczej `FoodOrderService`, albo w razie braku pomysłu `OrderServiceImpl`.
Co ta klasa ma właściwie wspólnego z Providerami, a nawet jeśli by miała - to czy warto to umieszczać w nazwie?

2020-09-30 16:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/service/InformationService.java
> +    void sendMessageUser(User user);
Niegramatyczna nazwa. `sendMessageToUser` byłoby OK.

2020-09-30 16:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/model/provider/ExtraFoodShop.java
> +    private final ProviderName providerName;
Generalnie ma sens, żeby dostawca miał swoją nazwę (ale do nazw używamy `String`-ów, nie `enum`-ów). 
Możesz spokojnie usunąć to pole, bo nie wykorzystujesz go nigdzie.

2020-09-30 16:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/model/provider/ProviderName.java
> +public enum ProviderName {
Ten `enum` w ogóle nie jest potrzebny (patrz inna uwaga).

2020-09-30 20:59 UTC, tomOsuch commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderDto.java
> +    private final BigDecimal price;
Tak tutaj myślałem o sumie cen wszystkich produktów, ale owszem lepiej dodać do produktu cenę detaliczną i potem zaimplementować cenę koszyka

2020-10-01 16:33 UTC, marszelun requested changes

2020-10-01 16:33 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderProcessor.java
> +            } throw new Exception();
1. Sprawdzałeś, czy Twój kod działa tak jak powinien? Jeśli nie piszesz testu, to powinieneś przynajmniej go uruchomić ;)
Tutaj niezależnie od wartości `isOrderSuccessfulProvider` rzucasz wyjątek, więc za każdym razem będzie wywołane to co w `catch`. Chyba zapomniałeś o `else` ;)
2. To metoda `orderService.order` powinna rzucać wyjątek, jeśli coś pójdzie nie tak. I wywołanie jej powinno być w `try`. W związku z tym zauważ, że `orderService.order` może być typu `void`.

2020-10-01 16:33 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderProcessor.java
> +        boolean isOrderSuccessfulProvider = orderService.order(orderRequest.getProducts());
Niegramatyczna nazwa. Po co tutaj słowo `Provider`? Wystarczy `isOrderSuccessful`.

2020-10-01 16:33 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderServiceImpl.java
> +                .allMatch(a -> a.equals(true));
Wyjątek miał być rzucany z tej metody.
Albo możesz tutaj użyć `if`-a i rzucać wyjątek dla wartości `false`, albo użyć metody `peek` wewnątrz strumienia i tam rzucić wyjątek dla pierwszego elementu, który jest `false`.

2020-10-01 16:33 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/model/provider/ExtraFoodShop.java
Jedna rzecz mi umknęła we wcześniejszej iteracji code review - interfejs `Provider` definiuje metodę `process()`. Przecież ta metoda musi przyjmować argument - listę produktów, które chcesz zamówić.
Przerób proszę na `process(Map<Product, Integer>)`.

2020-10-01 22:58 UTC, tomOsuch commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/model/provider/ExtraFoodShop.java
Mam tutaj pytanie czy poza zmianą przyjmowanego argumentu w tej implementacji ma coś się zmienić, czyli na jeśli produkt == "Krewetki" => return false

2020-10-02 01:12 UTC, tomOsuch commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderServiceImpl.java
> +                .map(Provider::process)
Tutaj niestety nie miałem pomysłu jak utworzyć taki strumień aby dostać List<Map<Product, Integer>>. Oczywiście przez rozmową jeszcze w tym temacie pomyśle.

2020-10-02 16:33 UTC, marszelun requested changes

2020-10-02 16:33 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/model/provider/ExtraFoodShop.java
Na potrzeby tego zadania nie musi.

2020-10-02 16:33 UTC, marszelun commented on kodilla-good-patterns/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.4.2'
Możesz sprawdzić, czy wszystkie 4 zależności trzeba koniecznie tutaj wskazywać. 
Niektóre zależności ładują inne zależności (tzw. _zależności tranzytywne_).
Przykład - jeśli dodajesz `spring-boot-starter-web`, nie musisz dodawać już `spring-boot-starter`, gdyż `spring-boot-starter-web` sam ładuje `spring-boot-starter`.

2020-10-02 16:33 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderServiceImpl.java
> +                .map(b -> b.process(products))
Tomek, w tej metodzie dla każdego elementu mapy (czyli dla każdego produktu) wywołujesz metodę `process`, podając jej całą mapę produktów.
Czyli zamawiasz u dostawców całą listę produktów tyle razy, ile jest produktów (niech mapa ma 8 elementów -> zamawiasz 64 produkty o swoich dostawców).
Rozbij to sobie proszę na 2 etapy, tak jak pisałem we wcześniejszych komentarzach:
1. Zamień mapę na 3 mapy, w każdej niech będą produkty tylko jednego dostawcy.
2. Dla każdej z tych map zamów tylko raz u danego dostawcy.
Jak będzie Ci to działać, napisz testy i potem spróbuj zamienić to na jeden stream.

PS, Produkcyjnie to by tak pewnie nie wyglądało, ale spacjalnie "męczę Cię", bo widzę że potrzebna jest powtórka ze strumieni ;)

2020-10-02 16:33 UTC, marszelun commented on kodilla-good-patterns/src/test/java/com/kodilla/good/patterns/food2door/order/OrderProcessorTest.java
> +public class OrderProcessorTest {
Zacznij od OrderServiceTest. Będzie dużo łatwiej...

2020-10-02 16:33 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/ExceptionOrder.java
> +public class ExceptionOrder extends RuntimeException {
`OrderException`.
Klasy wyjątku, jeśli mają w nazwie `Exception` (to dobra praktyka - wtedy od razu widać bez wchodzenia do pliku, że to klasa wyjątku), mają to słowo **zawsze** na końcu.

2020-10-03 08:00 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderServiceImpl.java
> +                .map(Provider::process)
Nie musisz używać do tego strumienia. Możesz na początek użyć zwykłej pętli for (przeiterować się po entrysecie).

2020-10-03 13:33 UTC, tomOsuch commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderServiceImpl.java
> +                .map(b -> b.process(products))
nie wiem czy to o to chodziło i czy w dobrym kierunku idę: nie chciałem robić całego Commit-u
```
products.entrySet().stream()
                .collect(Collectors.toList()).stream()
                .map(a -> a.getKey().getProvider().process(products))
                .allMatch(process -> process.equals(true));
```

2020-10-03 13:35 UTC, tomOsuch commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderServiceImpl.java
> +                .map(b -> b.process(products))
Na początku zamieniam na `List<Map<Product, Integer>>` a następnie otwieram sprawdzam wartości dla metody process ale chyba tutaj dalej przechodzę przez całą mapę. Nie wiem czy dokładnie o to chodziło.

2020-10-03 14:06 UTC, tomOsuch commented on kodilla-good-patterns/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.4.2'
Z tego co zobaczyłem w drzewku Gradle to chyba 2 zależności takie jak:
`org.junit.jupiter:junit-jupiter-engine: 5.6.2` oraz `org.junit.jupiter:junit-jupiter-params:5.4.2` są ładowane w `org.junit.jupiter:junit-jupiter-api:5.6.2`

2020-10-03 21:08 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderServiceImpl.java
> +                .map(b -> b.process(products))
Postaw pułapkę w metodach `process`, uruchom debugger i zobacz, ile razy się wywołują i z jakimi argumentami.
Nie przywiązuj się tak bardzo do streamów.
Napisz metodę, która rozbija mapę na 3 i wrzuca je do listy. Ta metoda nie będzie trywialna, ale nie potrzebujesz używać streamów. Możesz pomocniczo stworzyć sobie `Map<Provider, Map<Product, Integer>>`...
Jak to zadziała, możesz pobawić się z https://www.baeldung.com/java-groupingby-collector

Powtarzam ;) potrzebujesz takiej funkcji:
```
List<Map<Product, Integer>> groupByProvider(Map<Product, Integer>) { ... }
```
```

2020-10-03 21:09 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderServiceImpl.java
> +                .map(b -> b.process(products))
Spróbuj to jeszcze przełożyć na "prawdziwe życie". Masz listę (w Javie mapę) zamawianych produktów wraz z ilościami. Grupujesz je według dostawców i potem dzwonisz **raz** do każdego z dostawców, przekazując pełną listę produktów od tego dostawcy, których porzebujesz.

2020-10-07 15:43 UTC, marszelun requested changes

2020-10-07 15:43 UTC, marszelun commented on kodilla-good-patterns/build.gradle
>      testCompile group: 'junit', name: 'junit', version: '4.12'
Nie potrzebujesz jednocześnie junit4 i junit5. Zdecyduj się na jedną wersję (oczywiście lepiej 5).

2020-10-07 15:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderRequestRetriever.java
> +        cardProducts = Map.of(
`cartProducts` (koszyk to `cart`)

2020-10-07 15:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderRequest.java
> +    public BigDecimal price;
Raczej cena nie jest tu potrzebna, a jeśli musi być - to zmień nazwę (np. `totalAmount`) i zadbaj, aby była faktyczną sumą cen produktów w koszyku.

2020-10-07 15:43 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderServiceImpl.java
> +                .map(providerProducts -> providerProducts.getKey().process(providerProducts.getValue()))
Alternatywnie można by zrobić tak, wewnątrz `map`:
```
providerProducts -> {
   if(!providerProducts...) throw new OrderException();
}
```
Wtedy przetwarzanie zostałoby przerwane przy pierwszym dostawcy,  u którego proces się nie powiódł.
Nie zmieniaj - to tylko podpowiedź alternatywnego sposobu.

2020-10-07 15:43 UTC, marszelun commented on kodilla-good-patterns/src/test/java/com/kodilla/good/patterns/food2door/order/OrderServiceTest.java
> +    private OrderService orderServiceMock;
Nie potrzebujesz tutaj mocka `OrderService`. Raczej przyda Ci się mock dostawcy, żeby w świadomy sposób decydować o tym, czy zwróci `true` czy `false` w wywołaniu `process`.

2020-10-09 15:15 UTC, marszelun requested changes

2020-10-09 15:15 UTC, marszelun commented on kodilla-good-patterns/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.4.2'
No to spróbuj, żeby w Twoim pliku `build.gradle` było mniej wpisów (jak jedna biblioteka ładuje drugą, to nie musisz tej drugiej jawnie podawać).
Nie ptorzebujesz też `junit` w wersji 4, skoro korzystasz z 5.

2020-10-09 15:15 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/model/Product.java
> -    private final BigDecimal price;
Czemu produkt nie ma ceny?

2020-10-09 15:15 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/order/OrderRequestRetriever.java
> +        cartProduct = Map.of(
Nazwij to po prostu `cart`.

2020-10-09 15:15 UTC, marszelun commented on kodilla-good-patterns/src/test/java/com/kodilla/good/patterns/food2door/order/OrderServiceTest.java
> +        Map<Product, Integer> orders = createOrderFalse();
Po co tworzysz tę zmienną? I tak jej nie wykorzystujesz (w drugim teście podobnie).

2020-10-09 15:15 UTC, marszelun commented on kodilla-good-patterns/src/test/java/com/kodilla/good/patterns/food2door/order/OrderServiceTest.java
> +    private Map<Product, Integer> createOrderFalse() {
Minusem tego testu jest to, że musisz wiedzieć, który ze sklepów co zwraca. Lepiej użyć mocka i tutaj to jawnie określić, dla odmiany sklepy mogą nazywać się zupełnie inaczej niż w kodzie `main`.

2020-10-10 10:47 UTC, tomOsuch commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/model/Product.java
> -    private final BigDecimal price;
W sumie tutaj już nie chciałem komplikować i pisać metod sumujących koszyk. ale tak naprawdę produkt może mieć cenę detaliczną.

2020-10-10 11:29 UTC, tomOsuch commented on kodilla-good-patterns/src/test/java/com/kodilla/good/patterns/food2door/order/OrderServiceTest.java
> +        Map<Product, Integer> orders = createOrderFalse();
zauważyłem ten błąd po zrobieniu commit-u

2020-10-10 14:05 UTC, tomOsuch commented
Zmieniłem test na mockowane pola `Provider`. Jednak przez to nie wiem gdzie robie błąd ale pierwszy test nie przechodzi.

2020-10-10 17:52 UTC, marszelun commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/model/Product.java
> -    private final BigDecimal price;
Nie rozumiem. To jest klasa `Product`. Czyli mówi o produkcie. Produkt powinien mieć cenę. Produkt nie wie nic o koszyku, o jakim sumowaniu mowa?

2020-10-10 17:58 UTC, marszelun commented
> Zmieniłem test na mockowane pola `Provider`. Jednak przez to nie wiem gdzie robie błąd ale pierwszy test nie przechodzi.
Przede wszystkim metoda `createOrder` wprowadza tutaj więcej zamieszania, niż pożytku. Łatwiej będzie ogarnąć te testy, gdy w każdym z nich stworzysz odrębnie i bezpośrednio zamówienie.
Bezpośrednia przyczyna niepoprawnego działania - mocki, które tworzysz w testach są nigdzie nieużywane, bo w metodzie `createOrder` też tworzysz mocki, one są używane, ale nie są skonfigurowane (czyli metoda `process` zwraca na nich prawdopodobnie `null`).

2020-10-10 18:00 UTC, tomOsuch commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/food2door/components/model/Product.java
> -    private final BigDecimal price;
Tak, racja zgadzam się, bardziej mówiąc sumowanie myślałem o cenie dla całego koszyka ;)

2020-10-13 17:34 UTC, marszelun commented on kodilla-good-patterns/src/test/java/com/kodilla/good/patterns/food2door/order/OrderServiceTest.java
> +        Map<Product, Integer> orders = createOrderFalse();
Zawsze możesz wrzucić kolejny commit :) Dopóki link wstawiony w kodilli jest do PR-a, to możesz wrzucać ile commitów chcesz.

2020-10-14 09:30 UTC, merged