14.1 - bean ForumUser
tomOsuch/kodilla-course pull request #20
Opened 2020-10-02 15:00 UTC by tomOsuch

2020-10-02 16:44 UTC, marszelun requested changes

2020-10-02 16:44 UTC, marszelun commented on kodilla-spring/src/test/java/com/kodilla/spring/forum/ForumUserTestSuite.java
> +        ForumUser user = new ForumUser();
Obiekt klasy `ForumUser` ma jako bean być pobrany z kontekstu aplikacji (z `context`).

Zauważ, że przy teście napisanym tak jak obecnie, `context` jest w ogóle niepotrzebny, jak i adnotacja `@Component` oraz cały Spring ;)

Pamiętaj co jest celem testu: sprawdzenie, że bean typu `ForumUser` wyciągany z kontekstu został utworzony **przez Springa** przy użyciu jego konstruktora.

2020-10-02 20:05 UTC, tomOsuch commented on kodilla-spring/src/test/java/com/kodilla/spring/forum/ForumUserTestSuite.java
> +        ForumUser user = new ForumUser();
Ok dobra chyba zrozumiałem ten problem ;)

2020-10-03 08:04 UTC, marszelun approved these changes

2020-10-03 10:09 UTC, merged