task_14_2_calculator
tomOsuch/kodilla-course pull request #21
Opened 2020-10-03 17:26 UTC by tomOsuch

2020-10-03 20:44 UTC, marszelun requested changes

2020-10-03 20:44 UTC, marszelun commented on kodilla-spring/src/test/java/com/kodilla/spring/calculator/CalculatorTestSuite.java
> +        //Then
Brakuje asercji ;) a gdyby tak metody `Calculator` oprócz wyświetlania wartości, zwracały dodatkowo wynik?

2020-10-03 20:44 UTC, marszelun commented on kodilla-spring/src/main/java/com/kodilla/spring/calculator/Calculator.java
> +    public Calculator(Display display) {
Generalnie wstrzykiwanie przez konstruktor jest lepsze, ale żeby wypróbować różnych opcji, polecenie brzmiało: `Użyj wstrzykiwania przez właściwość klasy do powiązania obiektów klas Calculator oraz Display ze sobą.` (właściwość to inaczej pole).

PS. W przypadku wstrzykiwania przez konstruktor, w nowszych wersjach Springa adnotacja `@Autowired` nie jest potrzebna.

2020-10-03 20:50 UTC, tomOsuch commented on kodilla-spring/src/main/java/com/kodilla/spring/calculator/Calculator.java
> +    public Calculator(Display display) {
Czeli tutaj przez setter chodzi o wstrzyknięcie zależności?

2020-10-03 20:52 UTC, marszelun commented on kodilla-spring/src/main/java/com/kodilla/spring/calculator/Calculator.java
> +    public Calculator(Display display) {
Nie, przez właściwość (przez pole). Adnotacja `@Autowired` powinna być nad polem.

2020-10-03 20:58 UTC, tomOsuch commented on kodilla-spring/src/main/java/com/kodilla/spring/calculator/Calculator.java
> +    public Calculator(Display display) {
A to wtedy IntelliJ nie krzyczy że jest to nie rekomendowane ;) ?

2020-10-03 21:11 UTC, marszelun commented on kodilla-spring/src/main/java/com/kodilla/spring/calculator/Calculator.java
> +    public Calculator(Display display) {
Patrz początek tego wątku dyskusji: `generalnie wstrzykiwanie przez konstruktor jest lepsze` ;)
Może krzyczeć, ale jak zobaczysz taki kod (starszy), to musisz wiedzieć, o co chodzi.
+ wstrzykiwanie przez właściwość jest bardzo przydatne w testach (po prostu wstawiasz potrzebne beany jako pola).

2020-10-03 21:13 UTC, marszelun requested changes

2020-10-03 21:13 UTC, marszelun commented on kodilla-spring/src/main/java/com/kodilla/spring/calculator/Calculator.java
> +    }
Możesz teraz spokojnie usunąć konstruktor ;)

2020-10-04 08:29 UTC, marszelun approved these changes

2020-10-04 18:48 UTC, merged