task_14_3_ToDoList
tomOsuch/kodilla-course pull request #22
Opened 2020-10-04 10:36 UTC by tomOsuch

2020-10-04 22:36 UTC, tomOsuch commented
Tutaj chyba potrzebuję mała podpowiedz gdyż nie jestem pewien co do testu `testTaskAdd()`. Nie jestem pewien czy dobrą drogą szedłem tworząc setty dla pól Board i dodając przez konstruktor. Czy jednak nie lepiej abym napisał metodę prywatną w testach która by dodawała Listę tasków?

2020-10-05 15:40 UTC, marszelun requested changes

2020-10-05 15:40 UTC, marszelun commented on kodilla-spring/src/test/java/com/kodilla/spring/portfolio/BoardTestSuite.java
> +        boardTodo.setToDoList(new TaskList(List.of("test1", "test2")));
Nie, tutaj właśnie nie masz tworzyć obiektów `TaskList` ręcznie.
Wystarczy że wyciągniesz jedną listę (np. todo) z obiektu typu `Board`, dodasz do niej jakiś element, do drugiej listy (np. inprogress) dodasz inny. Asercją może być sprawdzenie, że listy się nie mieszają między sobą (tzn. element dodany do todolisty jest tylko w todoliście itp.)

2020-10-05 15:40 UTC, marszelun commented on kodilla-spring/src/test/java/com/kodilla/spring/portfolio/BoardTestSuite.java
> +        Board boardTodo = context.getBean(Board.class);
Niezrozumiama idea klasy `Board`. Tablica jest jedna i ma 3 typy list. Potrzebujesz przywoływać tylko jeden obiekt klasy `Board`.

2020-10-05 15:40 UTC, marszelun commented on kodilla-spring/src/test/java/com/kodilla/spring/portfolio/BoardTestSuite.java
> +        System.out.println("todo: " + boardToDo + "; inProg: " + boardInProg + "; done: " + boardDone);
Czy możesz wyjaśnić ideę tego testu? Co on ma sprawdzać?

2020-10-05 15:40 UTC, marszelun commented on kodilla-spring/src/test/java/com/kodilla/spring/portfolio/BoardTestSuite.java
> +        boolean boardToDo = context.containsBean("todo");
Sprawdzasz obiekt typu `TaskList`, a zmienna ma w nazwie `board`...

2020-10-05 15:40 UTC, marszelun commented on kodilla-spring/src/main/java/com/kodilla/spring/portfolio/Board.java
> +    public void setToDoList(TaskList toDoList) {
Settery w `Board` nie są w tym zadaniu do niczego potrzebne.

2020-10-05 15:40 UTC, marszelun commented on kodilla-spring/src/main/java/com/kodilla/spring/portfolio/Board.java
> +    private TaskList toDoList;
`final`

2020-10-05 15:40 UTC, marszelun commented on kodilla-spring/src/main/java/com/kodilla/spring/portfolio/BoardConfig.java
> +        return new Board(toDoList, inProgList, doneList);
Ogólnie to jest OK, natomiast można to zrobić prościej / bardziej elegancko. Możesz całkowicie zrezygnować z pól i zmienić `getBoard()` na `getBoard(@Qualifier("todo") TaskList todoList, @Qualifier("inprog") TaskList inProgList, @Qualifier("done") TaskList doneList)`. Co więcej, jeśli odpowiednio ponazywasz argumenty tej metody, możesz też zlikwidować adnotacje `@Qualifier` i Spring nadal sobie z tym poradzi.

2020-10-05 21:09 UTC, tomOsuch commented on kodilla-spring/src/test/java/com/kodilla/spring/portfolio/BoardTestSuite.java
> +        System.out.println("todo: " + boardToDo + "; inProg: " + boardInProg + "; done: " + boardDone);
tutaj myślałem o tym jakie Bean-y zostały załadowane do kontenera. Ale w sumie już zmieniłem ten test na inny który wypisze tablice bean-ów ;)

2020-10-06 16:21 UTC, marszelun approved these changes

2020-10-06 16:21 UTC, marszelun commented on kodilla-spring/src/test/java/com/kodilla/spring/portfolio/BoardTestSuite.java
> +        Arrays.stream(context.getBeanDefinitionNames())
W tym teście mógłbyś sprawdzić, czy Twoja lista zawiera konkretne beany jako asercja ;)

2020-10-08 18:44 UTC, merged