task_15_2_prototype
tomOsuch/kodilla-course pull request #25
Opened 2020-10-14 22:01 UTC by tomOsuch

2020-10-15 15:01 UTC, marszelun requested changes

2020-10-15 15:01 UTC, marszelun commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +        assertEquals(10, clonedLibrary.books.size());
Co te asercje mają dowieść?
To powinny być dwa niezależne testy - jeden testujący płytkie kopiowanie, drugi głębokie.
Jaki jest sens płytkiego kopiowania? Że w sklonowanym obiekcie będziesz miał referencję na ten sam zbiór. Czyli np. jeśli na sklonowanym dodasz element do zbioru, to w oryginalnym też go zobaczysz.
Przeciwnie, przy głębokim kopiowaniu, zostanie utworzony nowy zbiór i dodanie elementu w klonie nie ma wpływu na oryginał.
Pole typu `String` - tutaj mamy do czynienia z niemutowalnym obiektem, nadpisanie go setterem nie ma wpływu na oryginał (bo zmieniasz referencję) dla obu rodzajów kopiowania.
To właśnie powinno zostać przetestowane...

2020-10-17 09:43 UTC, marszelun requested changes

2020-10-17 09:43 UTC, marszelun commented on kodilla-patterns/src/main/java/com/kodilla/patterns/prototype/library/Library.java
> +    Set<Book> books = new HashSet<>();
Czemu pola nie są `private`?

2020-10-17 09:43 UTC, marszelun commented on kodilla-patterns/src/main/java/com/kodilla/patterns/prototype/library/Library.java
> +            cloneLibrary.getBooks().add(book);
Raz korzystasz z pola (`cloneLibrary.books`), raz z gettera (`cloneLibrary.getBooks()`). Ujednolić to proszę.

2020-10-17 09:43 UTC, marszelun commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +        assertEquals(clonedLibrary.getBooks(), library.getBooks());
Gdzie asercja na nazwę oryginalnego i sklonowanego obiektu?

2020-10-17 09:43 UTC, marszelun commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +        assertNotEquals(deepClonedLibrary.getBooks(), library.getBooks());
To jest słaba asercja. Nie weryfikuje poprawnego działania metody. Łatwiej by było, gdybyś miał 2 elementy w zbiorze, zamiast 10. Powinieneś sprawdzać zarówno obiekt oryginalny, jak i sklonowany.

2020-10-17 09:43 UTC, marszelun commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +        IntStream.iterate(1, n -> n = n + 1)
Tworzenie książek jest zdublowane (2x to samo w dwóch testach) - powinno być wydzielone do metody prywatnej.
Poza tym wystarczą 2 książki, zamiast 10 - po prostu możesz je wtedy dodać dwa razy wywołując `add`.
Generalnie takie tworzenie 10 książek, jeszcze przy pomocy streama, tylko odwraca uwagę od tego, co jest istotne w tym teście ;)

2020-10-18 17:07 UTC, tomOsuch commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +        assertNotEquals(deepClonedLibrary.getBooks(), library.getBooks());
W sumie nie rozumiem jak zastąpić tą asercje w teście sprawdzając zarówno obiekt oryginalny i klonowany. 
Dodałem assercje sprawdzające `hashCode()` na `getBooks()`

2020-10-18 17:07 UTC, tomOsuch commented
Nie przesyłałem linku w kursie gdyż nie jestem pewien czy o to chodziło a nie chce tam robić bałaganu ;)

2020-10-19 21:04 UTC, marszelun commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +        assertNotEquals(deepClonedLibrary.getBooks(), library.getBooks());
Ja bym to zrobił tak:
given: obiekt oryginalny z dwoma książkami,
when: obiekt sklonowany (w pierwszym teście płytko, w drugim głęboko), na obiekcie sklonowanym ustawiam inną nazwę i usuwam jedną z książek
then:
a) kl. płytkie - sprawdzam, że w oryginalnym jest oryginalna nazwa, w sklonowanym nowa, oba posiadają dokładnie 1 książkę i sprawdzam która to książka (ta nieusunięta)
b) kl. głębokie - sprawdzam, że w oryginalnym jest oryginalna nazwa, w sklonowanym nowa, oryginał posiada dokładnie 2 książki (sprawdzam jakie), klon posiada dokładnie 1 książkę i sprawdzam która to książka (ta nieusunięta)

2020-10-19 21:09 UTC, marszelun requested changes

2020-10-19 21:09 UTC, marszelun commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +        clonedLibrary = library.shallowCopy();
1. Czemu nie zrobisz tego w jednej linii - po prostu `Library clonedLibrary = library.shallowCopy()`?
2. Moim zdaniem czytelniej byłoby pozbyć się adnotacji `@BeforeEach` i po prostu tworzyć od nowa bibliotekę w każdym z testów: `Library originalLibrary = createLibrary()`.

2020-10-19 21:09 UTC, marszelun commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +        assertEquals(clonedLibrary.getBooks().hashCode(), library.getBooks().hashCode());
Jak sprawdziłeś równość obiektów pobieranych przez `.getBooks()`, to nie ma już sensu sprawdzać dodatkowo ich `hashCode`. Musi być taki sam, skoro to równe obiekty.

2020-10-21 19:00 UTC, marszelun requested changes

2020-10-21 19:00 UTC, marszelun commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +        assertNotEquals(deepClonedLibrary.getBooks(), originalLibrary.getBooks());
Podobnie, ta asercja wydaje się zbędna - łączna prawdziwość poprzednich asercji implikuje prawdziwość tej. Do usunięcia.

2020-10-21 19:00 UTC, marszelun commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +    Book addBook = new Book("Title 1", "Author 1", LocalDate.now());
1. Pola nazywają się jak metody. Lepsze byłyby: `book` i `bookToRemove` (książka i książka do usunięcia).
2. Czemu nie `private final`? W testach nie ma żadnego powodu, aby te pola nie były prywatne i finalne.

2020-10-22 17:18 UTC, marszelun requested changes

2020-10-22 17:18 UTC, marszelun commented on kodilla-patterns/src/test/java/com/kodilla/patterns/prototype/library/LibraryTestSuite.java
> +        assertEquals(2, originalLibrary.getBooks().size());
Mógłbyś jeszcze sprawdzić nazwę z `originalLibrary`.

2020-10-22 17:18 UTC, marszelun approved these changes

2020-10-23 22:18 UTC, merged