task_15_4_factory
tomOsuch/kodilla-course pull request #27
Opened 2020-10-18 15:14 UTC by tomOsuch

2020-10-19 00:18 UTC, tomOsuch commented
Tutaj się zastanawiam nad implementacją przedstawienia Task-ów w jakiejś mapie:
`Map<Task, Boolean>`?. I nie jestem pewien czy może jeszcze nie trzeba czegoś przetestować

2020-10-19 14:33 UTC, marszelun requested changes

2020-10-19 14:33 UTC, marszelun commented on kodilla-patterns/src/main/java/com/kodilla/patterns/factory/tasks/TaskFactory.java
> +    public final Task makeTask(final String taskClass) {
`createTask`

2020-10-19 14:33 UTC, marszelun commented on kodilla-patterns/src/main/java/com/kodilla/patterns/factory/tasks/TaskFactory.java
> +    public final Task makeTask(final String taskClass) {
Lepiej byłoby użyć `enum`-a zamiast `String`-a.

2020-10-19 14:33 UTC, marszelun commented on kodilla-patterns/src/test/java/com/kodilla/patterns/factory/task/TaskFactoryTestSuite.java
> +    }
W testach brakuje sprawdzenia, czy utworzone obiekty są oczekiwanego typu (możesz użyć operatora `instaceof`).
Mógłbyś też weryfikować, że bezpośrednio po utworzeniu `isTaskExecuted()` zwraca false.

2020-10-20 14:30 UTC, marszelun approved these changes

2020-10-20 14:30 UTC, marszelun commented on kodilla-patterns/src/main/java/com/kodilla/patterns/factory/tasks/TaskFactory.java
> -            default -> null;
To kolejna zaleta skorzystania z `enum`-a - nie musisz martwić się o obsługę nieprawidłowej wartości.

2020-10-21 09:43 UTC, merged