task_17_3_create-invoice
tomOsuch/kodilla-course pull request #33
Opened 2020-10-27 18:46 UTC by tomOsuch

2020-10-28 21:00 UTC, marszelun requested changes

2020-10-28 21:00 UTC, marszelun commented on kodilla-hibernate/src/test/java/com/kodilla/hibernate/invoice/dao/InvoiceDaoTestSuite.java
> +        assertNotEquals(0, computer.getId());
Jak będzie `null`, to asercja też przejdzie ;) Użyłbym `assertNotNull`.

2020-10-28 21:07 UTC, tomOsuch commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/invoice/Invoice.java
> +    public void setItems(List<Item> items) {
w sumie teraz ten setter juz nie musi być publiczny. Nigdzie w teście jego nie wykorzystuje.

2020-10-28 21:07 UTC, tomOsuch commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/invoice/Item.java
> +    public void setProduct(Product product) {
Tutaj tak samo jak dla settera w klasie `Invoice`

2020-10-28 21:15 UTC, tomOsuch commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/invoice/Product.java
> +    private List<Item> itemsProduct = new ArrayList<>();
tzn jeżeli tutaj nie przypisze domyślnej wartości to mam rozumieć że powinienem w teście np. wprowadzić wartość przez setter? np.: `computer.setItemsProduct(new ArrayList<>());`

2020-10-29 15:31 UTC, marszelun approved these changes

2020-10-29 18:24 UTC, merged

2020-10-31 17:05 UTC, marszelun commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/invoice/Product.java
> +    private List<Item> itemsProduct = new ArrayList<>();
No a nie możesz po prostu dodać kolejnego argumentu do konstruktora? No bo do czego Ci ta lista?