task_24_1_Fasada
tomOsuch/kodilla-course pull request #35
Opened 2021-01-11 22:51 UTC by tomOsuch

2021-01-20 18:07 UTC, marszelun requested changes

2021-01-20 18:07 UTC, marszelun commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/dao/CompanyDao.java
> +    List<Company> searchCompanyByPartName(@Param("PARTName") String name);
1. Bardziej gramatycznie byłoby `ByNamePart`.
2. Czemu argument ma niestandardową postać `PARTName`? (chodzi mi o użycie małych i wielkich liter)?

2021-01-20 18:07 UTC, marszelun commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/dao/EmployeeDao.java
> +    List<Employee> findByFewLetters(@Param("ARG") String letters);
W tym kontekście raczej zamiast `letters` używamy `characters`, w skrócie często `chars`.
Szukamy po znakach, nie po literach. W nazwie firmy może być np. `&`, `.` lub `!`, a to nie są litery.

2021-01-20 18:07 UTC, marszelun commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/facade/SearchFacade.java
> +            LOGGER.error(SearchFacadeException.ERR_COMPANY_NOT_FOUND);
W funkcjonalności wyszukiwarki nie powinniśmy stosować wyjątku do wskazania braku wyników. Jest to normalny, prawidłowy rezultat działania wyszukiwarki, a nie sytuacja wyjątkowa.
Poza tym, wyjątek ma mało mówiącą nazwę: `SearchFacadeException`; nazwa mówi tylko tyle że jest związany z `SearchFacade`, nic konkretnego.

2021-01-20 18:07 UTC, marszelun commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/facade/SearchFacade.java
> +            throw new SearchFacadeException(SearchFacadeException.ERR_EMPLOYEE_NOT_FOUND);
Podobnie jw.

2021-01-20 18:07 UTC, marszelun commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/facade/SearchFacadeException.java
> +    public static String ERR_COMPANY_NOT_FOUND = "Cannot find such company name";
Złamanie zasady pojedynczej odpowiedzialności.
Albo tworzysz bardziej ogólny wyjątek (np. po prostu `NotFoundException`), albo odrębne wyjątki dla pracowników i firm.
(patrz też inna uwaga - moim zdaniem w ogóle nie powinno być tutaj tego wyjątku).

2021-01-20 18:07 UTC, marszelun commented on kodilla-hibernate/src/test/java/com/kodilla/hibernate/manytomany/dao/facade/SearchFacadeTestSuite.java
> +        try {
Tego `try..catch` nie powinno tutaj być (patrz inne uwagi).

2021-01-20 18:07 UTC, marszelun commented on kodilla-hibernate/src/test/java/com/kodilla/hibernate/manytomany/dao/facade/SearchFacadeTestSuite.java
> +            List<Company> companies = searchFacade.findCompanies("ma");
(pytanie kontrolne, nie błąd ;) ) W którym miejscu aplikacji dzieje się to, że wielkość liter w wyszukiwanej frazie nie ma znaczenia?

2021-01-20 18:17 UTC, tomOsuch commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/dao/CompanyDao.java
> +    List<Company> searchCompanyByPartName(@Param("PARTName") String name);
racja przy drugiej uwadze chyba capslock się wyłączył ;)

2021-01-24 21:22 UTC, marszelun approved these changes

2021-01-24 21:22 UTC, marszelun commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/Company.java
> +        query = "FROM Company WHERE name LIKE Concat('%', :LETTERS, '%')"
Znaki `%` możesz posklejać w kodzie javovym. Niepotrzebnie angażujesz tutaj MySQL-ową funkcję `concat`.

2021-01-24 21:22 UTC, marszelun commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/Employee.java
> +        query = "SELECT * FROM EMPLOYEES WHERE LASTNAME LIKE Concat('%', :LETTERS, '%') OR FIRSTNAME LIKE Concat('%', :LETTERS, '%')",
Mówiliśmy, żeby użyć raczej słowa `characters` niż `letters`.

2021-01-24 21:22 UTC, marszelun commented on kodilla-hibernate/src/main/java/com/kodilla/hibernate/manytomany/dao/CompanyDao.java
> +    List<Company> searchCompanyByPartName(@Param("LETTERS") String name);
jw. `characters` zamiast `letters`.

2021-02-09 01:12 UTC, merged