task-24-2-Decorator
tomOsuch/kodilla-course pull request #36
Opened 2021-01-15 00:00 UTC by tomOsuch

2021-01-20 18:12 UTC, marszelun requested changes

2021-01-20 18:12 UTC, marszelun commented on kodilla-patterns2/src/main/java/com/kodilla/patterns2/decorator/pizza/PepperoniPizzaDecorator.java
> +        return super.getDescription() + ", Pepperoni," + " Salami";
wystarczy jeden `+`

2021-01-20 18:12 UTC, marszelun commented on kodilla-patterns2/src/main/java/com/kodilla/patterns2/decorator/pizza/PepperoniPizzaDecorator.java
> +        return super.getDescription() + ", Pepperoni," + " Salami";
Gdy użyjesz dekoratorów `Pepperoni` i `Salami`, salami będzie w opisie 2 razy. Czy to zamierzone zachowanie?

2021-01-20 18:12 UTC, marszelun commented on kodilla-patterns2/src/test/java/com/kodilla/patterns2/decorator/pizza/PizzaOrderTestSuite.java
> +        assertEquals("Pizza, Tomato Sauce, Mozzarella, Pepperoni, Salami", description);
Ten test przechodzi? Z lektury kodu wynika, że Salami powinno być dodane 2 razy ;)

2021-01-20 18:12 UTC, marszelun commented on kodilla-patterns2/src/test/java/com/kodilla/patterns2/decorator/pizza/PizzaOrderTestSuite.java
> +        pizzaOrder = new PizzaArugulaDecorator(pizzaOrder);
Nazwa testu nie pokrywa się z treścią, `testPizzaSalamiAndArugula...`?

2021-01-20 18:12 UTC, marszelun commented on kodilla-patterns2/src/test/java/com/kodilla/patterns2/decorator/pizza/PizzaOrderTestSuite.java
> +    public void testBasicPizzaOrderGetCost() {
To może kwestia gustu, ale wydaje mi się że słowo `Get` w nazwach tych testów jest zbędne. Testujesz, czy zgadza się koszt lub opis, słówko `Get` wygląda jakbyś chciał zwrócić uwagę na testowanie gettera...

2021-01-24 01:35 UTC, tomOsuch commented on kodilla-patterns2/src/main/java/com/kodilla/patterns2/decorator/pizza/PepperoniPizzaDecorator.java
> +        return super.getDescription() + ", Pepperoni," + " Salami";
Faktycznie, lekkie przeoczenie już wprowadzam poprawkę. Pojawi się przy następnym commicie.

2021-01-24 11:08 UTC, marszelun approved these changes

2021-01-24 11:51 UTC, merged