task-30-3-UpdateBestsellers
tomOsuch/kodilla-course pull request #40
Opened 2021-02-01 21:40 UTC by tomOsuch

2021-02-01 21:58 UTC, marszelun requested changes

2021-02-01 21:58 UTC, marszelun commented on kodilla-jdbc/src/test/java/com/kodilla/jdbc/StoredProcTestSuite.java
> +        int howMany = -1;
Troszkę czytelniej byłoby użyć `Integer` z wartością `null`. Ewentualnie użyć 0, ale tu patrz uwaga niżej.

2021-02-01 21:58 UTC, marszelun commented on kodilla-jdbc/src/test/java/com/kodilla/jdbc/StoredProcTestSuite.java
> +        String sqlCheckTable = "SELECT COUNT(*) AS HOW_MANY FROM BOOKS WHERE BESTSELLER = NULL";
1. Nigdy nie stosuj w SQL-u porównania do NULL. Zawsze da `FALSE`. https://www.xaprb.com/blog/2006/05/18/why-null-never-compares-false-to-anything-in-sql/
Poprawna składnia: `WHERE BESTSELLER IS NULL`
2. Trochę nie rozumiem, czemu do sprawdzenia procedury `UpdateBestsellers` sprawdzasz, ile książek nie ma ustawionego bestsellera, zamiast sprawdzić, ile ma? To takie sprawdzanie nie wprost.
3. `HOW_MANY` - bardzo nieznacząca nazwa kolumny. Może `BOOKS_WITHOUT_BESTSELLER_SET`? Tutaj wracam do uwagi z pkt. 2, lepiej sprawdzać np. `BESTSELLERS_COUNT`.

2021-02-01 21:58 UTC, marszelun commented on kodilla-jdbc/src/test/java/com/kodilla/jdbc/StoredProcTestSuite.java
> +        assertEquals(0, howMany);
Jak wyżej, więcej wartości byłoby w sprawdzeniu, ile JEST bestsellerów, a nie w ilu rekordach niczego nie ustawiono.
Jeśli chciałbyś sprawdzić na prawdę wszystko (myślę, że nie jest to wymagane w tym zadaniu), mógłbyś zgrupować po bestsellerze (`GROUP BY BESTSELLER`) i sprawdzić `COUNT`-a dla 3 możliwych wartości: `TRUE, FALSE, NULL`.

2021-02-02 02:17 UTC, tomOsuch commented
Do przegadania jak sprawdzić wszystko po przez `GROUP BY BESTSELLER`

2021-02-04 16:42 UTC, marszelun requested changes

2021-02-04 16:42 UTC, marszelun commented on kodilla-jdbc/src/test/java/com/kodilla/jdbc/StoredProcTestSuite.java
> +    @ValueSource(strings = {"= TRUE;", "= FALSE;", "IS NULL;"})
średnik jest wspólnym elementem - nie musi być częścią parametru (może być dodany na stałe w kodzie testu)

2021-02-04 16:42 UTC, marszelun commented on kodilla-jdbc/src/test/java/com/kodilla/jdbc/StoredProcTestSuite.java
> +        if (sqlWhere.equals("= TRUE;")) {
To nie wygląda zbyt dobrze. Powinieneś użyć 2 parametrów - jeden opisujący predykat (czyli `sqlWhere`), drugi opisujący oczekiwaną liczbę rekordów (typu `int`). Wtedy asercja będzie jedną linią, bez potrzeby pisania takich ifów.

2021-02-04 16:42 UTC, marszelun commented on kodilla-jdbc/src/test/java/com/kodilla/jdbc/StoredProcTestSuite.java
> +        }
Wg mnie sekcja `then` powinna się zaczynać tutaj - po wyznaczeniu `bestsellerCount`. To jest wielkość, którą badasz, wszystkie kroki zmierzające do jej utworzenia powinny być w sekcji `when`. Ładniej możesz to sobie napisać przy pomocy pomocniczej metody prywatnej.

2021-02-05 09:11 UTC, tomOsuch commented
NIe wiem czy to o to chodziło ?

2021-02-09 01:35 UTC, merged