task-31-3-testDelete
tomOsuch/kodilla-course pull request #43
Opened 2021-02-07 11:54 UTC by tomOsuch

2021-02-07 12:34 UTC, marszelun requested changes

2021-02-07 12:34 UTC, marszelun commented on kodilla-testing2/src/test/java/com/kodilla/testing2/crudapp/CrudAppTestSuite.java
> +        while(!driver.findElement(By.xpath("//select[1]")).isDisplayed());
1. Niebezpieczna pętla - jeśli element się nie pojawi, Twój test będzie wykonywał się w nieskończoność.
2. Odnosisz się do kolejności elementów, spróbuj inaczej wybrać tego selecta.

2021-02-07 12:34 UTC, marszelun commented on kodilla-testing2/src/test/java/com/kodilla/testing2/crudapp/CrudAppTestSuite.java
> +                    WebElement button = theForm.findElement(By.xpath(".//button[4]"));
Tu podobnie - odnosisz się do kolejności elementów.

2021-02-07 12:34 UTC, marszelun commented on kodilla-testing2/src/test/java/com/kodilla/testing2/crudapp/CrudAppTestSuite.java
> +        Thread.sleep(5000);
Do czego to potrzebne?

2021-02-07 15:41 UTC, tomOsuch commented on kodilla-testing2/src/test/java/com/kodilla/testing2/crudapp/CrudAppTestSuite.java
> +        Thread.sleep(5000);
W sumie racja przy tej metodzie nie ma to żadnego zastosowania.

2021-02-08 17:41 UTC, marszelun requested changes

2021-02-08 17:41 UTC, marszelun commented on kodilla-testing2/src/test/java/com/kodilla/testing2/crudapp/CrudAppTestSuite.java
> -        while(!driver.findElement(By.xpath("//select[1]")).isDisplayed());
Czy to na pewno można bezpiecznie usunąć? Nie trzeba czekać na pojawienie się tego elementu?
W moim komentarzu chodziło mi o inny sposób poczekania na element, niż pętlą while, nie o usunięcie.
No chyba, że to nie jest potrzebne - Ty mi powiedz :)

2021-02-09 00:55 UTC, tomOsuch commented on kodilla-testing2/src/test/java/com/kodilla/testing2/crudapp/CrudAppTestSuite.java
> -        while(!driver.findElement(By.xpath("//select[1]")).isDisplayed());
a tak faktycznie trzeba poczekać on odrazu nie jest widoczny... ;) zaraz poprawie błąd

2021-02-09 01:09 UTC, tomOsuch commented
znalazłem zastosowanie w takich sytuacjach implementacji Explicit Wait lub Implicit Wait w tym przypadku lepsze wydaje mi się zastosować ten pierwszy wariant ;)

2021-02-09 16:03 UTC, marszelun requested changes

2021-02-09 16:03 UTC, marszelun commented on kodilla-testing2/src/test/java/com/kodilla/testing2/crudapp/CrudAppTestSuite.java
> +        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//select[1]")));
z waitem ok, ale znów odnosisz się do kolejności elementu

2021-02-09 16:03 UTC, marszelun commented on kodilla-testing2/src/test/java/com/kodilla/testing2/crudapp/CrudAppTestSuite.java
> +                        anyForm.findElement(By.xpath(".//fieldset[1]/p[@class=\"datatable__field-value\"]"))
Tutaj również odniesienie do kolejności elementu

2021-02-09 21:28 UTC, marszelun approved these changes

2021-02-09 21:28 UTC, marszelun commented on kodilla-testing2/src/test/java/com/kodilla/testing2/crudapp/CrudAppTestSuite.java
> +                        anyForm.findElement(By.xpath(".//fieldset[@class=\"datatable__row-section datatable__row-section--input-section\"]/p[@class=\"datatable__field-value\"]"))
Tu dla odmiany można zastanowić się, czy potrzebne są aż dwie klasy, aby zidentyfikować ten element....

2021-03-08 23:21 UTC, merged